from dependency import *


def TaskMonitor(func):

    def wrapper(*args,**kwargs):
        signature = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Times New Roman; font-size:90%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
            """
        outlook = Dispatch('outlook.application')
        mail = outlook.CreateItem(0)
        mail.To = 'hiepdang@phs.vn'
        try:
            func(*args,**kwargs)
            mail.Subject = f"{func.__name__} Run Successfully"
        except (Exception,):
            mail.Subject = f"{func.__name__} Got Error"
        mail.HTMLBody = signature
        mail.Send()

    return wrapper
