from dependency import *


def TaskMonitor(func):

    def wrapper(*args,**kwargs):
        signature = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Times New Roman; font-size:90%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
            """
        try:
            func(*args,**kwargs)
            outlook = Dispatch('outlook.application')
            mail = outlook.CreateItem(0)
            mail.To = 'hiepdang@phs.vn'
            mail.Subject = f"{func.__name__} Run Successfully"
            mail.HTMLBody = signature
            mail.Send()
        except (Exception,):
            outlook = Dispatch('outlook.application')
            mail = outlook.CreateItem(0)
            mail.To = 'hiepdang@phs.vn'
            mail.Subject = f"{func.__name__} Got Error"
            mail.HTMLBody = signature
            mail.Send()

    return wrapper
