"""
This module simply brings functions from reporting package to implementation package
to ensure consistent workflow among projects.
"""

from request.stock import *

from reporting.trading_service.giaodichluuky import BaoCaoCheckGia
from reporting.trading_service.giaodichluuky import BaoCaoDanhSachChungKhoanSSI
from reporting.trading_service.giaodichluuky import BaoCaoDongMoUyQuyenTK_HNX
from reporting.trading_service.giaodichluuky import BaoCaoDongMoUyQuyenTK_HOSEnew
from reporting.trading_service.giaodichluuky import BaoCaoDongMoUyQuyenTK_HOSEold
from reporting.trading_service.giaodichluuky import BaoCaoHoatDongLuuKyNDTNN
from reporting.trading_service.giaodichluuky import BaoCaoTamTinhPhiChuyenKhoan
from reporting.trading_service.giaodichluuky import BaoCaoTamTinhPhiGiaoDich
from reporting.trading_service.giaodichluuky import BaoCaoTamTinhPhiLuuKy
from reporting.trading_service.giaodichluuky import BaoCaoTienGuiSSC
from reporting.trading_service.giaodichluuky import BaoCaoTinhHinhHDKD

from reporting.trading_service.thanhtoanbutru import BaoCaoDoiChieuLaiTienGuiPhatSinh_p1
from reporting.trading_service.thanhtoanbutru import BaoCaoDoiChieuLaiTienGuiPhatSinh_p2
from reporting.trading_service.thanhtoanbutru import BaoCaoDoiChieuSoDuTaiKhoanKhachHang
from reporting.trading_service.thanhtoanbutru import BaoCaoDoiChieuTTBTTienMuaBanChungKhoan
from reporting.trading_service.thanhtoanbutru import BaoCaoDoiChieuUTTB
from reporting.trading_service.thanhtoanbutru import BaoCaoDoiChieuVaImportEIB
from reporting.trading_service.thanhtoanbutru import BaoCaoDoiChieuVaImportOCB
from reporting.trading_service.thanhtoanbutru import BaoCaoDuLieuGuiKiemToan
from reporting.trading_service.thanhtoanbutru import BaoCaoFileGhiAmGuiKSNB
from reporting.trading_service.thanhtoanbutru import BaoCaoFileImportTKNganHangBuoiSang
from reporting.trading_service.thanhtoanbutru import BaoCaoKHNNCoSoDuNho
from reporting.trading_service.thanhtoanbutru import BaoCaoPhatSinhGiaoDichTien
from reporting.trading_service.thanhtoanbutru import BaoCaoPSTheoDoiTKKHCanChuyenTienTuVSDVeTKGD
from reporting.trading_service.thanhtoanbutru import BaoCaoReviewKHVIPCoSo
from reporting.trading_service.thanhtoanbutru import BaoCaoSoDuTienKyQuyPhaiSinh
from reporting.trading_service.thanhtoanbutru import BaoCaoSoLieuThongKeDVTC
from reporting.trading_service.thanhtoanbutru import BaoCaoUngTienROS
from reporting.trading_service.thanhtoanbutru import BaoCaoXacNhanNopRutEIBOCB
from reporting.trading_service.thanhtoanbutru import DanhSachKHVIPCoSo
from reporting.trading_service.thanhtoanbutru import DanhSachKHVIPPhaiSinh
from reporting.trading_service.thanhtoanbutru import BaoCaoSoDuTienKyQuyPhaiSinh

"""
Cần viết tool gửi mail đá lỗi, giao diện GUI retry + email báo có chênh lệch trong các BC đối chiếu 
(as decorators that wrap functions from reporting package)
"""
